experiment_name: "fashion-mnist-v1"

log_path: "results/fashion-mnist-v1"
tensorboard_path: "results/fashion-mnist-v1/runs"

dataset:
  path: "data"
  name: "fashion-mnist"
  batchsize: 300
  n_workers: 8

training:
  n_epochs: 300
  seed: 10
  log_interval: 100
  snapshot_interval: 500
  log_samples_interval: 500
  n_log_samples: 10 # save (value) x (value) grid image
  grad_max_norm: 8

optimizer:
  gen:
    lr: 0.0002
    decay: 0.00001
  dis:
    lr: 0.0002
    decay: 0.00001

models:
  dis:
    use_noise: true
    noise_sigma: 0.05

latent_variables:
  -
    name: "z"
    kind: "z"
    prob: "normal"
    dim: 64
    mu: 0
    var: 1

  -
    name: "c1"
    kind: "c"
    prob: "categorical"
    dim: 1
    k: 10
    weight: 1.0

  -
    name: "c2"
    kind: "c"
    prob: "normal"
    dim: 1
    mu: 0
    var: 1
    weight: 0.1

  -
    name: "c3"
    kind: "c"
    prob: "normal"
    dim: 1
    mu: 0
    var: 1
    weight: 0.1
