experiment_name: "mnist_v1"

log_path: "results/mnist_v1"
tensorboard_path: "results/mnist_v1/runs"

dataset:
  path: "data"
  name: "mnist"
  batchsize: 200
  n_workers: 8

training:
  n_epochs: 100
  seed: 0
  log_interval: 100
  snapshot_interval: 1000
  log_samples_interval: 1000

optimizer:
  gen:
    lr: 0.0002
    decay: 0.00001
  dis:
    lr: 0.0002
    decay: 0.00001

models:
  dis:
    use_noise: false
    noise_sigma: 0.2

latent_variables:
  - 
    name: "z"
    kind: "z"
    prob: "normal"
    dim: 64
    mu: 0
    var: 1

  - 
    name: "c1"
    kind: "c"
    prob: "categorical"
    dim: 1
    k: 10
    weight: 1
