# add c variable
experiment_name: "mnist_v3"

log_path: "results/mnist_v3"
tensorboard_path: "results/mnist_v3/runs"

dataset:
  path: "data"
  name: "mnist"
  batchsize: 1000
  n_workers: 8

training:
  n_epochs: 100
  seed: 0
  log_interval: 100
  snapshot_interval: 500
  log_samples_interval: 500

optimizer:
  gen:
    lr: 0.0002
    decay: 0.00001
  dis:
    lr: 0.0002
    decay: 0.00001

models:
  dis:
    use_noise: false
    noise_sigma: 0.01

latent_variables:
  - 
    name: "z"
    kind: "z"
    prob: "normal"
    dim: 64
    mu: 0
    var: 1

  - 
    name: "c1"
    kind: "c"
    prob: "categorical"
    dim: 1
    k: 10
    weight: 1

  - 
    name: "c2"
    kind: "c"
    prob: "uniform"
    dim: 1
    min: -1
    max: 1
    weight: 0.1

  # - 
  #  name: "c3"
  #  kind: "c"
  #  prob: "normal"
  #  dim: 1
  #  mu: 0
  #  var: 1
